### ISSUE TITLE
Nullary predicates are not shown in argument maps

### ISSUE THREAD

**Issue by tfgordon** [carneades/carneades-4#17]
Suppose the language is defined as follows:

language:
  offer/0:  "An offer has been made."
  acceptance/0: "The offer has been accepted."
  contract/0: "A contract has been made."
  insane/0: "One of the parties is insane."

These four nullary predicates represent propositional letters, i.e atoms.  The problem is that in argument maps, statements constructed using these predicates are shown as empty boxes.

**Comment by tfgordon** [comment]
Here is a full example illustrating this issue:

meta:
  title: Exceptions and Hierarchies Example 1
  source: >
    Henry Prakken and Giovanni Sartor. Law and logic: a review from an
    argumentation perspective.  Artificial Intelligence. 2015.

language:
  offer/0:  "%s is an offer."
  acceptance/0: "The offer has been accepted."
  contract/0: "A contract has been made."
  insane/0: "One of the parties is insane."

argument_schemes:
  r1:
    premises:
      - offer
      - acceptance
    conclusions:
      - contract
    exceptions:
      - insane
  r2:
    premises:
      - insane
    conclusions:
      - ¬contract

issue_schemes:
  negation:  ["¬P", "P"]

assumptions:
  - offer
  - acceptance
  - insane

**Comment by tfgordon** [comment]
I see now that defining nullary predicates in the language without stating the arity works, as in 

```
language:
  offer:  "An offer has been made."
  acceptance: "The offer has been accepted."
  contract: "A contract has been made."
  insane: "One of the parties is insane."
```

Shouldn't foo/0 and foo mean the same ?
