### ISSUE TITLE
Schemes with conclusion being a variable cause problems during instantiation

### ISSUE THREAD

**Issue by pallix** [carneades/carneades-4#25]
Hi Tom :),

When the premises of a scheme having a variable as a conclusion can be grounded with statements put in the `assumptions`, it fails to generate an argument but also blocks the generation for the other schemes.

For example the following file stops to produce any argument during the evaluation, when the commented lines are uncommented:

```
meta:
  title: Walton Argumentation Schemes
  notes: >
    Here we illustrate one way to represent many of the argumentation schemes of Doug Walton,
    including critical questions. 
  source: >
    Walton, Douglas and Reed, Chris and Macagno, Fabrizio (2008). 
    Argumentation Schemes. Cambridge University Press.

language:
  just/1: "just %s"
  in/2: "%s contains %s as a member."
  more_coherent_explanation/2: "There exists a more coherent explanation than theory %s of observation %s."
  observed/1:  "%s has been observed."
  explanation/2: "Theory %s explains %s."
  has_occurred/1: "An event %s has occurred."
  causes/2: "Event %s causes event %s."
  interference/1: "An event has occurred which interferes with event %s."
  will_occur/1: "An event %s will occur."

statements:
   expert(joe,climate): Joe is a climate expert.
   in_domain(¬caused_by(global_warming,humans),climate): >
      The claim that global warming is not caused by humans is in the climate domain.
   asserts(joe,¬caused_by(global_warming,humans)): >
      Joe asserts that global warming is not caused by humans.
   ¬caused_by(global_warming,humans): >
      Global warming is not caused by humans.
   based_on_evidence(asserts(joe,¬caused_by(global_warming,humans))): 
      "Joe's assertion is based on evidence."
   observed(s): observed
   explanation(t,s): explanation
   in(t,h): in

argument_schemes:

  # - id: abduction
  #   variables: [S,T,H]
  #   conclusions: [H]
  #   premises:
  #     - observed(S)
  #     - explanation(T,S)
  #     - in(T,H)
  #   exceptions:
  #     - more_coherent_explanation(T,S)

  - id: abduction_working
    variables: [S,T,H]
    conclusions:
      - just(H)
    premises:
      - observed(S)
      - explanation(T,S)
      - in(T,H)
    exceptions:
      - more_coherent_explanation(T,S)

assumptions:
  - observed(s)
  - explanation(t,s)
  - in(t,h)

```

Yours,
Pierre
