### ISSUE TITLE
Argument from scheme not generated when adding an assumption

### ISSUE THREAD

**Issue by pallix** [carneades/carneades-4#27]
Hi again,

I have this file where uncommenting the commented line causes the argument to not be generated from the scheme:

```
meta:
  title: something

language:
  concluded/1: "We conclude %s"
  to/2: "%s can conclude %s."
  rendered_obsolete/2: "Theory %s has been rendered obsolete, by some other unknown theory, for observation %s "
  observed/1:  "%s has been observed."
  from/2: "Theory %s can be used to conclude something from %s."
  has_occurred/1: "An event %s has occurred."
  causes/2: "Event %s causes event %s."
  interference/1: "An event has occurred which interferes with event %s."
  will_occur/1: "An event %s will occur."
  t/0: "Theory implies something "
  would_be_known/1: "%s would be known if it were true."
  uninvestigated/1: "The truth of %s has not been investigated."
  known/1: "%s is known to be true."

argument_schemes:

  - id: abduction
    variables: [S,T,H]
    conclusions:
      - concluded(H)
    premises:
      - observed(S)
      - from(T,S)
      - to(T,H)
    exceptions:
      - rendered_obsolete(T,S)

statements:
  technical_mistake: technical mistake
  ¬technical_mistake: not a technical mistake

assumptions:
  # - technical_mistake
  - observed(obs)
  - from(t,obs)
  - to(t,conc)

```
