### ISSUE TITLE
Deducting the premise of a scheme from a conclusion prevent its instantiation

### ISSUE THREAD

**Issue by pallix** [carneades/carneades-4#28]
Hi again,

In the example below, the scheme fails to be instantiated, because one of its premises, `observed(obs)` is deduced from an argument. Is it a bug? 

```
meta:
  title: something

language:
  concluded/1: "We conclude %s"
  to/2: "%s can conclude %s."
  rendered_obsolete/2: "Theory %s has been rendered obsolete, by some other unknown theory, for observation %s "
  observed/1:  "%s has been observed."
  from/2: "Theory %s can be used to conclude something from %s."
  has_occurred/1: "An event %s has occurred."
  causes/2: "Event %s causes event %s."
  interference/1: "An event has occurred which interferes with event %s."
  will_occur/1: "An event %s will occur."
  t/0: "Theory implies something "
  would_be_known/1: "%s would be known if it were true."
  uninvestigated/1: "The truth of %s has not been investigated."
  known/1: "%s is known to be true."

argument_schemes:

  - id: abduction
    variables: [S,T,H]
    conclusions:
      - concluded(H)
    premises:
      - observed(S)
      - from(T,S)
      - to(T,H)
    exceptions:
      - rendered_obsolete(T,S)

arguments:

  a:
    conclusion: observed(obs)
    premises:
      - heard(obs)

statements:
  technical_mistake: technical mistake
  ¬technical_mistake: not a technical mistake
  observed(obs): observed
  heard(obs): heard

assumptions:
  - heard(obs)
  - from(t,obs)
  - to(t,conc)
```
