### ISSUE TITLE
Assumption not appearing in the evaluated graph

### ISSUE THREAD

**Issue by pallix** [carneades/carneades-4#29]
Hi Tom,

In the example below the assumption `justTagged(d, and2)` does not appear in the evaluated graph if not defined in the statements. Is this expected?

In general it's not clear to me when terms or assumptions need to be in the statements or not.

```
meta:
  title: Multi-parameter logic call 'and' operator
  

language:
  just/1: "just %s"
  justTagged/2: "just %s of `and` with tag %s"
  and/3: "and(%s,%s,%s)"
  and/4: "and(%s,%s,%s) with tag %s"

argument_schemes:
  - id: s_and
    variables: [A,B,C]
    conclusions:
      - and(A,B,C)
    premises:
      - just(A)
      - just(B)
      - just(C)

  - id: s_and_tag
    variables: [A,B,C,T]
    conclusions:
      - and(A,B,C,T)
    premises:
      - justTagged(A, T)
      - justTagged(B, T)
      - justTagged(C, T)

statements:
  a: a
  b: b
  c: c
   # if not mentioned here, does not appear on the graph?
   # justTagged(d, and2): justTagged(d, and2)

assumptions:
  - ¬just(a)
  - just(b)
  - just(c)
  # - just(d)
  - justTagged(a, and1)
  - justTagged(b, and1)
  - justTagged(c, and1)
  - justTagged(d, and2)
```
