### ISSUE TITLE
Error when having a composed statement in the tests key

### ISSUE THREAD

**Issue by pallix** [carneades/carneades-4#35]
Hi,

I get `expected labeling: : not declared to be a statement: coin(b, head)` when uncommenting the last line. Am I doing something wrong?

```

statements:
  coin(a, head): coin(a, head)
  coin(b, head): coin(b, head)
  coin_a: coin_a

assumptions:
  - coin_a
  - coin(b, head)

tests:
  in:
    - coin_a
    # not working:
    # - coin(b, head)
```
