### ISSUE TITLE
Defining issues for compound terms

### ISSUE THREAD

**Issue by pallix** [carneades/carneades-4#36]
Is it possible to somehow define issues for compound terms without knowing in advance what the compound term will be? For example in the example below the domain of `person` is infinite (the domain of the first argument is infinite, there is potentially an infinite numbers of persons) but for a given person `p` we would really want to have:

```
issues:
  i1: 
    positions: 
      - person(p, alive)
      - ¬person(p, alive)
```

and potentially also
```
issues:
  i2: 
    positions: 
      - person(p, alive)
      - person(p, dead)
```

Whenever a new person is expressed in the system (for example with an assumption such as `born(lea)`), we need to add issues for `lea` such as the one above.

Is there a trick to simplify that?

```
meta:
  title: Identifying an inconsistency on a proposition

language:
  inconsistent/2: "%s has an inconsistent instance %s"
  breathing/1: "%s is breathing"
  killed/1: "%s was killed"
  person/2: "person %s is %s"
  alive/0: "alive"

statements:
  person(p,alive): p is alive
  ¬person(p,alive): ¬p is alive

argument_schemes:

  - id: breathing
    conclusions:
      - person(p,alive)
    premises:
      - breathing(p)

  - id: killed
    conclusions:
      - ¬person(p,alive)
    premises:
      - killed(p)

assumptions:
  - breathing(p)
  - killed(p)
```
